version: v8
data_local_save_dir: ./data/raw
dvc_remote_repo: https://github.com/rahulsm27/project_dvc.git
dvc_data_folder: data/raw
github_user_name: rahulsm27
github_access_token_secret_id: github
infrastructure:
  project_id: mlendtoend
  zone: europ2-west4-b
  network: default
dataset_reader_manager:
  _target_: src.data_processing.dataset_readers.DatasetReaderManager
  dataset_readers:
    ghc:
      _target_: src.data_processing.dataset_readers.GHCDatasetReader
      dataset_dir: ./data/raw/ghc
      dataset_name: ghc
      gcp_project_id: mlendtoend
      gcp_github_access_token_secret_id: github
      dvc_remote_repo: https://github.com/rahulsm27/project_dvc.git
      github_user_name: rahulsm27
      version: v8
      dev_split_ratio: 0.3
    jtc:
      _target_: src.data_processing.dataset_readers.JigsawToxicCommentsDatasetReader
      dataset_dir: ./data/raw/jigsaw
      dataset_name: jtc
      gcp_project_id: mlendtoend
      gcp_github_access_token_secret_id: github
      dvc_remote_repo: https://github.com/rahulsm27/project_dvc.git
      github_user_name: rahulsm27
      version: v8
      dev_split_ratio: 0.06
    twitter:
      _target_: src.data_processing.dataset_readers.TwitterDatasetReader
      dataset_dir: ./data/raw/cyberbull
      dataset_name: twitter
      gcp_project_id: mlendtoend
      gcp_github_access_token_secret_id: github
      dvc_remote_repo: https://github.com/rahulsm27/project_dvc.git
      github_user_name: rahulsm27
      version: v8
      dev_split_ratio: 0.25
      test_split_ratio: 0.2
  repartition: true
  available_memory: null
dataset_cleaner_manager:
  _target_: src.data_processing.dataset_cleaners.DatasetCleanerManager
  dataset_cleaners:
    stop_words:
      _target_: src.data_processing.dataset_cleaners.StopWordsDatasetCleaner
    to_lower_case:
      _target_: src.data_processing.dataset_cleaners.ToLowerCaseDatasetCleaner
    url:
      _target_: src.data_processing.dataset_cleaners.URLDatasetCleaner
    punctuation:
      _target_: src.data_processing.dataset_cleaners.PunctuationDatasetCleaner
      punctuation: '!"#$%&''()*+,-./:;<=>?@[\]^_`{|}~'
    non_letters:
      _target_: src.data_processing.dataset_cleaners.NonLettersDatasetCleaner
    new_line:
      _target_: src.data_processing.dataset_cleaners.NewLineCharacterDatasetCleaner
    non_ascii:
      _target_: src.data_processing.dataset_cleaners.NonASCIIDatasetCleaner
    referance:
      _target_: src.data_processing.dataset_cleaners.ReferanceToAccountDatasetCleaner
    re_tweet:
      _target_: src.data_processing.dataset_cleaners.ReTweetDatasetCleaner
    spell_correction:
      _target_: src.data_processing.dataset_cleaners.SpellCorrectionDatasetCleaner
      spell_correction_model:
        _target_: src.utils.utils.SpellCorrectionModel
        max_dictionary_edit_distance: 2
        prefix_length: 7
        count_threshold: 1
dask_cluster:
  _target_: dask.distributed.LocalCluster
  n_workers: 12
  memory_limit: auto
  processes: true
  threads_per_worker: 1
  scheduler_port: 8786
  silence_logs: 30
  host: null
  dashboard_address: :8787
  asynchronous: false
  blocked_handlers: null
  service_kwargs: null
  security: null
  protocol: null
  interface: null
  worker_class: null
processed_data_save_dir: ./data/processed
docker_image_name: europe-west4-docker.pkg.dev/mlendtoend/mlflow/src-data-preparation
docker_image_tag: C5C0DACD-DD94-497A-882E-694F8A35CFF7
